### ISSUE TITLE
delisting?

### ISSUE THREAD

**Issue by Elompenta** [bjorand/yasb#1]
How I'm able to delist a false positive?

**Comment by bjorand** [comment]
Yasb checks bad IP adresses with the following DNS blacklists: https://github.com/mrichman/godnsbl/blob/master/godnsbl.go#L18.
You should check if your IP is blacklisted there then Yasb will purge its records as it caches results with a Least Recent Used policy.

**Comment by Elompenta** [comment]
thanks 4 info!
